name       : psmisc
version    : '23.3'
release    : 5
source     :
    - https://deac-fra.dl.sourceforge.net/project/psmisc/psmisc/psmisc-23.3.tar.xz : 41750e1a5abf7ed2647b094f58127c73dbce6876f77ba4e0a7e0995ae5c7279a
license    : GPL-2.0-or-later
component  : system.base
summary    : PSMisc
description: |
    Small utilities that use the /proc filesystem
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
