name       : psmisc
version    : 23.2
release    : 2
source     :
    - https://kent.dl.sourceforge.net/project/psmisc/psmisc/psmisc-23.2.tar.xz : 4b7cbffdc9373474da49b85dc3457ae511c43dc7fa7d94513fe06f89dcb87880
license    : GPL-2.0-or-later
component  : system.base
summary    : PSMisc
description: |
    Small utilities that use the /proc filesystem
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
